apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-volumne
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany

  storageClassName: manual
  hostPath:
    path: /opt/volume/nginx
