apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: simple-webapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      name: grpc
  selector:
    app: simple-webapp
