apiVersion: batch/v1
kind: Job
metadata:
  name: throw-dice-job
spec:
  completions: 3
  backoffLimit: 25
  parallelism: 3
  template:
    spec:
      containers:
        - name: math-add
          image: kodekloud/throw-dice
      restartPolicy: Never
